id: P004205
initial_creation_type: ocr
source_metadata:
  id: bdr:W3JT13783
  title: སྤོ་ཆེན་རྒྱལ་བ་བློ་གྲོས་ཀྱི་ཆོས་སྤྱོད་མཐོང་བ་འཛུམ་ཤོར།
  author: ''
  volumes:
    9b8f680cc4fe41efbab66d24629d067f:
      image_group_id: I3JT13786
      title: ''
      volume_number: 1
      total_pages: 28
      base_file: v001.txt
