id: IF38F12FF
legacy_id: P004205
ocr_import_info:
  bdrc_scan_id: W3JT13783
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T09:00:24'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T17:07:05.413687+00:00'
last_modified: 2022-09-04 01:07:10.571160
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3JT13783
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3JT13783
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤོ་ཆེན་རྒྱལ་བ་བློ་གྲོས་ཀྱི་ཆོས་སྤྱོད་མཐོང་བ་འཛུམ་ཤོར།
  author: དགེ་བགྲེས་དམ་ཆོས་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.8546827399508301
  ocr_word_median_confidence_index: 0.9200000166893005
quality: null
bases:
  I3JT13786:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3JT13786
      total_pages: 28
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3JT13786.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8546827399508301
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
